In [2]:
import numpy as np
from numpy import random

In [12]:

k1 = list(range(10))
k1
len(k1)

10

In [22]:
a1 = np.arange(10)
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
len(a1)

10

In [26]:
a1[3]

3

In [30]:
a2=np.arange(4,15)
a2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
# last number of array would be <=24 (second input-1)
a3=np.arange(4,25,3)
a3

array([ 4,  7, 10, 13, 16, 19, 22])

In [59]:
a3=np.arange(40,5,-2)  #last number of the array would be >=6 (second input+1)
a3

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,
        6])

In [65]:
k1=[6,4,7,9,8,2]

In [67]:
a1=np.array(k1)

In [69]:
a1

array([6, 4, 7, 9, 8, 2])

In [71]:
type(k1)

list

In [73]:
type(a1)

numpy.ndarray

In [75]:
a1=np.append(a1,7) # appends the value at the last position 

In [77]:
a1

array([6, 4, 7, 9, 8, 2, 7])

In [79]:
a2 = np.array([4,3,7,6])

In [83]:
a1= np.concatenate((a1,a2))

In [85]:
a1

array([6, 4, 7, 9, 8, 2, 7, 4, 3, 7, 6])

In [87]:
a1 = np.insert(a1,3,7) # insert at index 3

In [89]:
a1

array([6, 4, 7, 7, 9, 8, 2, 7, 4, 3, 7, 6])

In [91]:
a1=np.delete(a1,5) # delte value from index number 5 
a1

array([6, 4, 7, 7, 9, 2, 7, 4, 3, 7, 6])

In [99]:
p1=[6,8,4,3]
p1

[6, 8, 4, 3]

In [103]:
p2=[4,5,1,7]
p2

[4, 5, 1, 7]

In [119]:
a2=np.array([p1,p2])
a2

array([[6, 8, 4, 3],
       [4, 5, 1, 7]])

In [111]:
a3=np.array([4,7,5,8,9])
a3

array([4, 7, 5, 8, 9])

In [123]:
a3.shape

(5,)

In [125]:
a2.shape

(2, 4)

In [143]:
a2 =np.array([[3,4,5,6,7],[3,4,5,6,8],[4,5,8,6,9]])

In [145]:
a2

array([[3, 4, 5, 6, 7],
       [3, 4, 5, 6, 8],
       [4, 5, 8, 6, 9]])

In [147]:
a2.shape

(3, 5)

In [10]:
a4 =np.array([3,4,5,6,8,9,2,3,4,5,6,5])
a4

array([3, 4, 5, 6, 8, 9, 2, 3, 4, 5, 6, 5])

In [12]:
len(a4)

12

In [14]:
a5=a4.reshape(3,4)

In [16]:
a5

array([[3, 4, 5, 6],
       [8, 9, 2, 3],
       [4, 5, 6, 5]])

In [20]:
a5[2]

array([4, 5, 6, 5])

In [22]:
a5[:,2] # for extracting column index 2 ot third column 

array([5, 2, 6])

In [24]:
a5[1][2] # extracts the values from 2nd row and 3rd column 

2

In [26]:
a5[[0,2]] # multiple row 

array([[3, 4, 5, 6],
       [4, 5, 6, 5]])

In [30]:
a5[:,[0,2]]

array([[3, 5],
       [8, 2],
       [4, 6]])

In [60]:
newr=np.array([5,6,7,2])

In [62]:
# add new row  using vstack 
a5=np.vstack([a5,newa5])

In [64]:
a5

array([[3, 4, 5, 6],
       [8, 9, 2, 3],
       [4, 5, 6, 5],
       [5, 6, 7, 2],
       [5, 6, 7, 2]])

In [68]:
# add new column 
newc1=np.array([4,8,7,1,2])

In [70]:
newc1=newc1.reshape(5,1)

In [72]:
newc1

array([[4],
       [8],
       [7],
       [1],
       [2]])

In [76]:
a5= np.hstack([a5,newc1])

In [78]:
a5

array([[3, 4, 5, 6, 4],
       [8, 9, 2, 3, 8],
       [4, 5, 6, 5, 7],
       [5, 6, 7, 2, 1],
       [5, 6, 7, 2, 2]])

In [80]:
a5.shape

(5, 5)

In [88]:
a5 = np.insert(a5,2,[3,6,7,5,9],axis=0)

In [96]:
a5

array([[3, 4, 5, 6, 4],
       [8, 9, 2, 3, 8],
       [3, 6, 7, 5, 9],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 5, 7],
       [5, 6, 7, 2, 1],
       [5, 6, 7, 2, 2]])

In [99]:
a5=np.insert(a5,3,[3,4,5,6,8,9,5],axis=1)

In [101]:
a5

array([[3, 4, 5, 3, 6, 4],
       [8, 9, 2, 4, 3, 8],
       [3, 6, 7, 5, 5, 9],
       [3, 6, 7, 6, 5, 9],
       [4, 5, 6, 8, 5, 7],
       [5, 6, 7, 9, 2, 1],
       [5, 6, 7, 5, 2, 2]])

In [103]:
a5=np.delete(a5,(3,6),axis=0)

In [105]:
a5

array([[3, 4, 5, 3, 6, 4],
       [8, 9, 2, 4, 3, 8],
       [3, 6, 7, 5, 5, 9],
       [4, 5, 6, 8, 5, 7],
       [5, 6, 7, 9, 2, 1]])

In [107]:
a5=np.delete(a5,(4),axis=1)

In [109]:
a5

array([[3, 4, 5, 3, 4],
       [8, 9, 2, 4, 8],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 8, 7],
       [5, 6, 7, 9, 1]])

In [113]:
a5.size
len(a5)

5

In [115]:
x2=np.arange(24)

In [117]:
x2=x2.reshape(4,3,2)

In [119]:
x2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [125]:
x2=np.array([2,3,4,5,6,7,8,9,5,43,2,22,5])

In [127]:
np.sort(x2)

array([ 2,  2,  3,  4,  5,  5,  5,  6,  7,  8,  9, 22, 43])

In [129]:
x2

array([ 2,  3,  4,  5,  6,  7,  8,  9,  5, 43,  2, 22,  5])

In [135]:
np.sort(a5,axis=0)  # top row will get leat value 

array([[3, 4, 2, 3, 1],
       [3, 5, 5, 4, 4],
       [4, 6, 6, 5, 7],
       [5, 6, 7, 8, 8],
       [8, 9, 7, 9, 9]])

In [136]:
a5

array([[3, 4, 5, 3, 4],
       [8, 9, 2, 4, 8],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 8, 7],
       [5, 6, 7, 9, 1]])

In [161]:
# broadcasting  # same command broadcasted to all the value of array 

In [143]:
x2

array([ 2,  3,  4,  5,  6,  7,  8,  9,  5, 43,  2, 22,  5])

In [145]:
x2[[1,5,7]]

array([3, 7, 9])

In [147]:
x3=list(x2)

In [149]:
x3

[2, 3, 4, 5, 6, 7, 8, 9, 5, 43, 2, 22, 5]

In [151]:
x4=np.array(x3)

In [153]:
x4

array([ 2,  3,  4,  5,  6,  7,  8,  9,  5, 43,  2, 22,  5])

In [155]:
t=[5,6,3]

In [157]:
t*2

[5, 6, 3, 5, 6, 3]

In [159]:
x2*2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 10, 86,  4, 44, 10])

In [165]:
x2

array([ 2,  3,  4,  5,  6,  7,  8,  9,  5, 43,  2, 22,  5])

In [167]:
x2*3

array([  6,   9,  12,  15,  18,  21,  24,  27,  15, 129,   6,  66,  15])

In [169]:
x2+3

array([ 5,  6,  7,  8,  9, 10, 11, 12,  8, 46,  5, 25,  8])

In [171]:
a5   

array([[3, 4, 5, 3, 4],
       [8, 9, 2, 4, 8],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 8, 7],
       [5, 6, 7, 9, 1]])

In [173]:
# to broadcast to 2d array 
x3=np.array([1,2,3,4,5])

In [175]:
x3+a5

array([[ 4,  6,  8,  7,  9],
       [ 9, 11,  5,  8, 13],
       [ 4,  8, 10,  9, 14],
       [ 5,  7,  9, 12, 12],
       [ 6,  8, 10, 13,  6]])

In [177]:
a5

array([[3, 4, 5, 3, 4],
       [8, 9, 2, 4, 8],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 8, 7],
       [5, 6, 7, 9, 1]])

In [179]:
x4=np.array([1,2,3,4,5])

In [181]:
x4=x4.reshape(5,1)

In [183]:
x4   # broadcast columns values 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [187]:
a5

array([[3, 4, 5, 3, 4],
       [8, 9, 2, 4, 8],
       [3, 6, 7, 5, 9],
       [4, 5, 6, 8, 7],
       [5, 6, 7, 9, 1]])

In [189]:
a5+x4   # adding column ot column 

array([[ 4,  5,  6,  4,  5],
       [10, 11,  4,  6, 10],
       [ 6,  9, 10,  8, 12],
       [ 8,  9, 10, 12, 11],
       [10, 11, 12, 14,  6]])

In [191]:
x2

array([ 2,  3,  4,  5,  6,  7,  8,  9,  5, 43,  2, 22,  5])

In [193]:
# input to the np.where command is a condition to be check or logical array , ouput of np.where command is list of indice where condition is found to be true 

In [195]:
x2<5

array([ True,  True,  True, False, False, False, False, False, False,
       False,  True, False, False])

In [205]:
t1=np.where(x2<5)
t1

(array([ 0,  1,  2, 10], dtype=int64),)

In [201]:
len(t1) # before  saving entire array as 1 enity , 2nd will come in 2d array 

1

In [207]:
len(t1[0])

4

In [209]:
x3=np.array([5,4,7,1,4,8,9,2,1,6,5])
# how  many values fullfill the criteria 
# where are values written in the array x3 which fulfill the criteria 
# what are values in the array x3 which fulfil the criteria 

In [211]:
x3

array([5, 4, 7, 1, 4, 8, 9, 2, 1, 6, 5])

In [217]:
(x3>=4).sum()

8

In [238]:
np.where(x3>=4)[0]


array([ 0,  1,  2,  4,  5,  6,  9, 10], dtype=int64)

In [242]:
len(np.where(x3>=4)[0]) # how  many values fullfill the criteria 

8

In [246]:
t1=np.where(x3>=4)[0] # where are values written in the array x3 which fulfill the criteria 
t1

array([ 0,  1,  2,  4,  5,  6,  9, 10], dtype=int64)

In [254]:
x3
x3[t1]


array([5, 4, 7, 4, 8, 9, 6, 5])

In [260]:
v=np.array([3,4,5,6,7,8,2])
v

array([3, 4, 5, 6, 7, 8, 2])

In [264]:
np.where(v%2==0)[0]

array([1, 3, 5, 6], dtype=int64)

In [266]:
len(np.where(v%2==0)[0])

4

In [268]:
t=np.where(v%2==0)[0]

In [272]:
 v[t]

array([4, 6, 8, 2])

In [274]:
x1

array([[3, 4, 5, 6, 4],
       [8, 9, 2, 3, 8],
       [4, 5, 6, 5, 7],
       [5, 6, 7, 2, 1],
       [5, 6, 7, 2, 2]])

In [276]:
np.where(x1>4)

(array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([2, 3, 0, 1, 4, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2], dtype=int64))

In [290]:
t1=np.where(x1>4)  # where are the values 
t1

(array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([2, 3, 0, 1, 4, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2], dtype=int64))

In [284]:
x1[t1] # what are the values 

array([5, 6, 8, 9, 8, 5, 6, 5, 7, 5, 6, 7, 5, 6, 7])

In [286]:
len(t1)

2

In [288]:
len(t1[0])  # how many values 

15

In [294]:
[3,4,5]*3 #rep(c(3,4,5),times=3)

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [298]:
np.repeat(np.array([3,4,5]),[2,4,6])  # rep(c(3,4,5),times=(2,4,6))

array([3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5])

In [306]:
x=np.array([5,8,3,6,9,3,2])

In [308]:
y =np.array([4,3,9,7,3,1])

In [312]:
np.intersect1d(x,y)

array([3, 9])

In [318]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [314]:
np.in1d(x,y)

array([False, False,  True, False,  True,  True, False])

In [316]:
np.where(np.in1d(x,y))

(array([2, 4, 5], dtype=int64),)

In [320]:
np.setdiff1d(x,y)

array([2, 5, 6, 8])

In [322]:
np.setdiff1d(y,x)

array([1, 4, 7])

In [324]:
np.setxor1d(y,x)

array([1, 2, 4, 5, 6, 7, 8])

In [4]:
from numpy import random

In [332]:
p1=np.random.rand(10)

In [334]:
p1

array([0.0230641 , 0.91405784, 0.58832459, 0.47741037, 0.83964798,
       0.7605179 , 0.68691282, 0.87886191, 0.3356887 , 0.87955898])

In [336]:
np.round(12.434334,3)

12.434

In [344]:
p1=np.round(np.random.rand(10),3)

In [340]:
p1

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [346]:
p2=np.random.randint(10,50)

In [348]:
p2

22

In [350]:
p2=np.random.randint(10,50,15)

In [352]:
p2

array([14, 12, 48, 11, 41, 26, 34, 11, 37, 13, 24, 42, 45, 39, 33])

In [378]:
len(p2)



15

In [418]:
n=np.round(np.random.randint(60,99,15))
n

array([89, 64, 98, 92, 63, 83, 95, 87, 63, 65, 87, 67, 71, 66, 94])

In [420]:
p2=np.round(np.random.rand(15),2)
p2

array([0.26, 0.15, 0.18, 0.9 , 0.75, 0.08, 0.95, 0.42, 0.07, 0.49, 0.38,
       0.94, 0.27, 0.55, 0.95])

In [422]:
n+p2

array([89.26, 64.15, 98.18, 92.9 , 63.75, 83.08, 95.95, 87.42, 63.07,
       65.49, 87.38, 67.94, 71.27, 66.55, 94.95])

In [6]:
### 
from numpy import linalg


In [8]:
arr1=np.array([[1,0,2],[1,1,1],[2,1,3]])

In [10]:
arr1

array([[1, 0, 2],
       [1, 1, 1],
       [2, 1, 3]])

In [16]:
np.linalg.det(arr1)

0.0

In [58]:
ar1=np.random.randint(1,5,size=(3,2))
ar1

array([[4, 1],
       [1, 1],
       [3, 4]])

In [66]:
ar2=np.random.randint(1,5,size=(3,2))
ar2

array([[3, 2],
       [4, 1],
       [1, 2]])

In [78]:
ar3=np.random.randint(1,5,size=(2,3))
ar3


array([[1, 3, 2],
       [1, 2, 2]])

In [72]:
np.matmul(ar1,ar2)   #3x2 X 3x2 = 9  #as column of 1st matrix must be equal to row of 2nd matrix 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [80]:
np.matmul(ar1,ar3)  

array([[ 5, 14, 10],
       [ 2,  5,  4],
       [ 7, 17, 14]])

In [96]:
a=np.array([[2,3,1],[0,1,-1],[1,2,-1]])

In [98]:
b=np.array([23,-3,3])

In [100]:
b=b.reshape(3,1)

In [102]:
a # 3x3


array([[ 2,  3,  1],
       [ 0,  1, -1],
       [ 1,  2, -1]])

In [104]:
b #3x1  

array([[23],
       [-3],
       [ 3]])

In [108]:
a_inv = np.linalg.inv(a) 

In [110]:
a_inv  # a_inverse is 3x3  x=A^-1   B    A 3x3  B 3x1 

array([[-0.5, -2.5,  2. ],
       [ 0.5,  1.5, -1. ],
       [ 0.5,  0.5, -1. ]])

In [112]:
np.matmul(a_inv,b)   # 3x1

array([[2.],
       [4.],
       [7.]])